### ISSUE TITLE
Main.py

### ISSUE THREAD

**Issue by kanishkasingh1993** [MQSchleich/OrcaNado#2]
Downloaded the repo and tried to run the main.py, gives an error on import automation.run_input as run_input , says module not found.  Am i missing something here ?
Edit : Commenting for run_input needed maybe ?

**Comment by kanishkasingh1993** [comment]
Note : Orca file must have exact path in *xyzfile command. If not orca cannot find the file. if file is fge.inp for example, replace the *xyzfile 0 1 fge.inp by *xyzfile 0 1 X:/inputs/fge.inp where  X:/ inputs ... is the exact file path. 
Not necessarily an error but a QOL change

**Comment by kanishkasingh1993** [comment]
Please put instructions for input test generation on the main page if possible.

**Comment by MQSchleich** [comment]
Hello,
I can't reproduce your errors. Please provide detailed instructions.

**Comment by kanishkasingh1993** [comment]
Just running the main.py file gives the error. Thats because automation folder does not have any file named run_input

**Comment by MQSchleich** [comment]
Hm. I don't see this error message. But I am still missing the test-files. Maybe you can push them here now, such that I may write the tests to avoid errors.

**Comment by kanishkasingh1993** [comment]
I have added files in automation/tests/ . Tested  before already though, FOWYOG gives the wrong results. The same behaviour is expected in FUYMUI, although it would be similar to FOWYOG due to ordering issues

**Comment by MQSchleich** [comment]
Thanks for uploading the tests. Yes, these were the problems discussed with Annika back more than 2 weeks ago. Are these the tests verified by Annika? How and when can you solve issues to FUYMUI and FOWYOG?

**Comment by kanishkasingh1993** [comment]
I really dont think you know what the problem is here. The problem is not with FOWYOG with how I do it. Its how you and probably annika discussed how to calculate it. That is what needs to be changed her, nothing for me to really do here. I have written to Annika before and will write again.

**Comment by MQSchleich** [comment]
It is no problem that there are no reliable test cases for me to verify the input generation against yet. We have some tough time communicating due to COVID-19. We will get it to work eventually.

**Comment by MQSchleich** [comment]
The project was discontinued by @kanishkasingh1993. The party decided to develop it further in a closed manner.
